#   Configure your program here and rename this file to 'client_config.toml' for changes to apply.
queue_user = '{Your personal username}'

#   [server]: 'ip address' and [server]: 'port' must be configured in order to function
#   'ip address' is the ip address of your server.
#   'port' must be the same as in 'server_config.toml'
[server]
ip_address = '{Your Server IP Address}'
port = '{Your Server Port}'